In [10]:
import pandas as pd
import numpy as np

In [25]:
mat = np.random.randint(8,34,size=(5,6))
print(mat)

[[28 12 15 11 26 27]
 [ 8 22 31 32 29 24]
 [ 9 17  9 17 19 28]
 [28 20 26 30 17 21]
 [11 10 31 10 19 23]]
