In [1]:
import numpy as np

## Task 0

In [39]:
d1 = np.array(10)
d2 = np.array([10,20])
d3 = np.array([[1,2],[3,4]])

d = [d1,d2,d3]

for i,obj in enumerate(d):
    print("\n {i}. \tDimension: {dim}".format(i=i+1, dim=obj.ndim) + '\n'
          "\tShape: {s}".format(s=obj.shape) + '\n' +
          "\tSize: {sz}".format(sz=obj.size) + '\n' +
           "---------------------\nArray:\n" + str(obj))


 1. 	Dimension: 0
	Shape: ()
	Size: 1
---------------------
Array:
10

 2. 	Dimension: 1
	Shape: (2,)
	Size: 2
---------------------
Array:
[10 20]

 3. 	Dimension: 2
	Shape: (2, 2)
	Size: 4
---------------------
Array:
[[1 2]
 [3 4]]


# 

## Task 1

In [40]:
t1 = np.array([np.zeros(10),np.ones(10),np.ones(10)*5])
print(t1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


## Task 2

In [41]:
t2 = np.arange(30,71,1)
print(t2)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


## Task 3

In [42]:
t3 = np.arange(30,71,2)
print(t3)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


## Task 4

In [43]:
a1 = np.array([10,20,30])
a2 = np.array([1,5,6])

sum = a1+a2
sub = a1-a2
mul = a1*a2
div = a1/a2

obj = [sum,sub,mul,div]

for i in obj:
    print(str(i)+'\n')

[11 25 36]

[ 9 15 24]

[ 10 100 180]

[10.  4.  5.]



In [48]:
a1 = np.array([[2,7],[10,5]])
a2 = np.array([[3,2],[15,1]])

sum = np.add(a1,a2)
sub = np.subtract(a1,a2)
mul = np.multiply(a1,a2)
div = np.divide(a1,a2)
asum = np.sum(a1)
amin = np.min(a1)
amax = np.max(a1)

obj = [sum,sub,mul,div,asum,amin,amax]

for i in obj:
    print(str(i)+'\n')

[[ 5  9]
 [25  6]]
[[-1  5]
 [-5  4]]
[[  6  14]
 [150   5]]
[[0.66666667 3.5       ]
 [0.66666667 5.        ]]
24
2
10
